### ISSUE TITLE
Can't build with Arch Linux

### ISSUE THREAD

**Issue by muellerjoel** [pietmacom/kopano-pkgbuilds#4]
It's fails to build mapi.so. I do with ./build-docker.sh build and also following apps aren't build.

kopano-configurator      kopano-webapp         python2-minimock
kopano-postfixadmin      libical2              python2-tlslite
kopano-sabre             perl-lockfile-simple  tidy
kopano-service-overview  php-xapian            z-push

Why?

**Comment by mpietruschka** [comment]
We solved that in the kopano chat on matrix.
